- name:   
  ansible.builtin.command: pip3.6 install -r requirements.txt   
  args:
      chdir: /app  
  when: "{{component}} == payment" 

 - name: "Setup SystemD {{component}} Service"
   ansible.builtin.copy:
    src: "{{component}}.service"
    dest: "/etc/systemd/system/{{component}}.service"

 - name: reload
   ansible.builtin.systemd_service:
      daemon_reload: true      

 - name: "enable {{component}}"
   ansible.builtin.service:
     name: "{{component}}"
     enabled: true
     state: started